### ISSUE TITLE
Sugestão de melhoria de código para determinar o RPM

### ISSUE THREAD

**Issue by plasmaXZ** [chrystianfarias/gta-fmod#12]
No arquivo "GTAFmod.cpp" tem uma linha pra determinar o RPM do veículo que está assim:
```
float currentRatio = (velocity - m_pTransmission->m_aGears[nGear].m_fChangeDownVelocity)
                / (*(float*)&m_pTransmission->m_aGears[nGear].m_fMaxVelocity
                    - m_pTransmission->m_aGears[nGear].m_fChangeDownVelocity);
```

Pelo que testei, se essa linha for assim:

`float currentRatio = velocity / m_pTransmission->m_aGears[nGear].m_fMaxVelocity;`

E mais embaixo, para determinar o targetRpm for assim:
```
float targetRpm = currentAudio->m_Ini->m_fMaxRPM * params->m_fVelocityChangingPercentage;
targetRpm = max(currentAudio->m_Ini->m_fMinRPM, targetRpm);
```

Podemos ter melhores resultados.
O único problema até agora que encontrei, é que o RPM máximo padrão do .bank do AE86 tem que ser em torno de 7200 RPM para não cortar giro o tempo todo.
Mas claro, não sei se há uma razão particular pro calculo ser mais complexo que o sugerido, se houver, por favor me avise.

https://github.com/chrystianfarias/gta-fmod/blob/a6203b2678a3b1bbf25d0a90cbef53a3bb56aa79/GTAFmod/GTAFmod.cpp#L196

Edit: Aqui está uma demonstração de como ficou 
https://www.youtube.com/watch?v=CYiMDqyAb3Y

**Comment by JuniorDjjr** [comment]
#16 implementado, mas eu deixei uma opção no .ini para o targetRpm antigo pois ele combina mais para dirigir na rua.
