### ISSUE TITLE
Handling Affected Negatively

### ISSUE THREAD

**Issue by HzanRsxa2959** [chrystianfarias/gta-fmod#3]
### A video showcasing the issue:
[![YouTube](http://i3.ytimg.com/vi/lWJafI4XpHY/hqdefault.jpg)](https://www.youtube.com/watch?v=lWJafI4XpHY)
### Here are my current INI settings:
```
[Audio]
MinRPM = 800
MidRPM = 4500
FinalRPM = 8000
MinRPMTorque = 0.8
MidRPMTorque = 1.2
FinalRPMTorque = 0.1
RPMVolume = 0.4
RPMAcceleration = 50
RPMDeceleration = 60
AutomaticGearbox = 1 ;1 = Automatic, 0 = Manual
PitchMultiply = 1

[Damage]
DamageWhenShiftingWrong = 0 ;1 = Damage, 0 = No damage
MaxRPMDamage = 800 ;8000+800 = 8800 RPM
DamageMultiply = 80

[GearRatio]
RelationR = -1
RelationN = 0
Relation1 = 3
Relation2 = 2
Relation3 = 1.6
Relation4 = 1.2
Relation5 = 0.9
Relation6 = 0.7

[Keys]
UpGearKey = 0 ;Shift
DownGearKey = 0 ;Ctrl
ClutchKey = 0 ;F7
```
### Something is off with the handling of vehicles:
- Most instances of bikes won't accelerate at all; **NRG-500**s do sometimes, and **HPV-1000** almost never.
- No vehicles ever reach full speed (shown with the **Bullet** at [2:19](https://www.youtube.com/watch?v=lWJafI4XpHY&t=139s) in the video above. Fixed by changing **AutomaticGearbox** to **Automatic** in the INI, so it's not really a bug but the effect of an obscure optional configuration. Just wanted to clarify).

**Comment by chrystianfarias** [comment]
Manual Gearbox removed, this bug is no longer happening.
